@elisoft.notification_HostAddress = http://localhost:5258/

POST {{elisoft.notification_HostAddress}}api/Notification/slack
Content-Type: application/json
X-API-KEY: XTd7wZYLSHbcdDRXPsxyVGeV8KfrU0JQ

{
  "Channel": "Slack",
  "Payload": {
    "message": "test"
  }
}