@elisoft.notification_HostAddress = http://localhost:5258/

POST http://localhost:5258/api/Notification/send
Content-Type: application/json
X-API-KEY: 

{
  "channel": "Slack",
  "payload": {
    "webhookUrl": "",
    "channelName": "#notificator",
    "message": "test"
  }
}